CREATE TABLE IF NOT EXISTS season (
    "id" VARCHAR(26) NOT NULL,
    "version" VARCHAR(26) NULL,
    "start_date" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "end_date" TIMESTAMP WITH TIME ZONE NULL,
    "active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("id")
);