CREATE TABLE IF NOT EXISTS bet_type (
    "id" VARCHAR(26) NOT NULL,
    "type" VARCHAR(26) NULL,
    "subtype" VARCHAR(26) NULL,
    "odd" DECIMAL(10, 2) NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("id")
);
